baseURL = "https://example.com"
title = "tidyverse tips"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = false
copyright = "&copy; Copyright Year 2020, Martin Frigaard"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/post/"
    weight = -100
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"
    weight = -90

# Configuration Features
[params]
  header_title = "Tidyverse Tips"                 # Your header title
  header_subtitle = "Martin's #rstats blog" # Your header subtitle
  home_image = "/images/avatar.png"          # Path to header image starting from the static directory
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog", "about"]   # Main sections to include in recent posts
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "http://github.com/mjfrigaard"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/mjfrigaard/"
  [[params.social]]
    fa_icon = "fab fa-twitter fa-1x"
    href = "https://twitter.com/mjfrigaard"
